apiVersion: apps/v1
kind: Deployment

metadata:
  name: devsecops-website

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devsecops

  template:
    metadata:
      labels:
        app: devsecops

    spec:
      containers:
        - name: website
          image: devsecops-website:latest
          ports:
            - containerPort: 80